EyeSeeTea/dhis2-android-sdk

app/src/main/java/org/hisp/dhis/android/sdk/persistence/Dhis2Database.java
app/src/main/java/org/hisp/dhis/android/sdk/persistence/migrations/version6/Version6AddCodeDataelement.java
app/src/main/java/org/hisp/dhis/android/sdk/persistence/models/DataElement.java

Attributes pull code dataelement

---

app/src/main/java/org/hisp/dhis/android/sdk/controllers/DhisController.java
app/src/main/java/org/hisp/dhis/android/sdk/controllers/DhisService.java
app/src/main/java/org/hisp/dhis/android/sdk/controllers/metadata/MetaDataController.java
app/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerController.java
app/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerDataSender.java
app/src/main/java/org/hisp/dhis/android/sdk/controllers/wrappers/ProgramWrapper.java
app/src/main/java/org/hisp/dhis/android/sdk/persistence/migrations/version6/Version6AddCodeDataelement.java
app/src/main/java/org/hisp/dhis/android/sdk/persistence/models/ProgramStageDataElement.java

Allows sdk api to get the result of each push (event)

Import summary 222

---

app/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerDataLoader.java

Max number of events can be changed

---

app/src/main/java/org/hisp/dhis/android/sdk/controllers/DhisController.java
app/src/main/java/org/hisp/dhis/android/sdk/controllers/DhisService.java
app/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerDataLoader.java

Pull data metadata

---

app/src/main/java/org/hisp/dhis/android/sdk/controllers/metadata/MetaDataController.java
app/src/main/java/org/hisp/dhis/android/sdk/controllers/wrappers/AssignedProgramsWrapper.java
app/src/main/java/org/hisp/dhis/android/sdk/network/DhisApi.java
app/src/main/java/org/hisp/dhis/android/sdk/persistence/Dhis2Database.java
app/src/main/java/org/hisp/dhis/android/sdk/persistence/migrations/version8/Version8AddOrganisationUnitColumns.java
app/src/main/java/org/hisp/dhis/android/sdk/persistence/models/OrganisationUnit.java
app/src/main/java/org/hisp/dhis/android/sdk/persistence/models/OrganisationUnitDataSet.java
app/src/main/java/org/hisp/dhis/android/sdk/persistence/models/OrganisationUnitGroup.java

closes #19 
@ifoche ! 
Only one thing.
I was setting the ancestors and the childrens as lists before ask and read your anwser. Should i remove it? You said me not touch it. But i was storing it before.
Thanks.

Retrieve all org units parameters

---

app/src/main/java/org/hisp/dhis/android/sdk/controllers/metadata/MetaDataController.java
app/src/main/java/org/hisp/dhis/android/sdk/controllers/wrappers/ProgramWrapper.java
app/src/main/java/org/hisp/dhis/android/sdk/persistence/models/DataElement.java
app/src/main/java/org/hisp/dhis/android/sdk/persistence/models/Program.java
app/src/main/java/org/hisp/dhis/android/sdk/persistence/models/ProgramAttributeValue.java

Program attributes

---

app/src/main/java/org/hisp/dhis/android/sdk/controllers/metadata/MetaDataController.java
app/src/main/java/org/hisp/dhis/android/sdk/controllers/wrappers/OrganisationUnitLevelWrapper.java
app/src/main/java/org/hisp/dhis/android/sdk/network/DhisApi.java
app/src/main/java/org/hisp/dhis/android/sdk/persistence/models/OrganisationUnitLevel.java

Loads orgunit levels

---

app/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerController.java
app/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerDataLoader.java

Adds setter to TrackerController since TrackerDataLoader is not public

---

app/src/main/java/org/hisp/dhis/android/sdk/controllers/DhisService.java
app/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerDataLoader.java
app/src/main/java/org/hisp/dhis/android/sdk/utils/log/LogMessage.java
app/src/main/java/org/hisp/dhis/android/sdk/utils/log/SdkLogger.java

Logs returns errors downloading events

---

app/src/main/java/org/hisp/dhis/android/sdk/controllers/metadata/MetaDataController.java

related #912 and [PR ](https://github.com/EyeSeeTea/malariapp/pull/916)

Added OptionAttributeValue in wipe tables.

---

app/src/main/java/org/hisp/dhis/android/sdk/controllers/wrappers/ProgramWrapper.java

Save all the program dataelements

---

app/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerController.java
app/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerDataLoader.java
app/src/main/java/org/hisp/dhis/android/sdk/network/DhisApi.java

Closes #40
And work with [pull_events_from_date](https://github.com/EyeSeeTea/malariapp/tree/pull_events_from_date) branch

Event query by date

---

app/src/main/java/org/hisp/dhis/android/sdk/controllers/metadata/MetaDataController.java

Related [issue](https://github.com/EyeSeeTea/malariapp/issues/928)

Pull organisationUnit ancestors

---

app/src/main/java/org/hisp/dhis/android/sdk/controllers/metadata/MetaDataController.java

Feature remove automatic ou retrieval

---

app/src/main/java/org/hisp/dhis/android/sdk/controllers/wrappers/OrganisationUnitLevelWrapper.java
app/src/main/java/org/hisp/dhis/android/sdk/network/DhisApi.java

Closes [issue](https://github.com/EyeSeeTea/malariapp/issues/1048)

Fixed bug in the organisationUnitLevels

---

core-android/src/main/java/org/hisp/dhis/client/sdk/android/event/EventInteractor.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/event/EventInteractorImpl.java
core/src/main/java/org/hisp/dhis/client/sdk/core/common/controllers/IdentifiableDataController.java
core/src/main/java/org/hisp/dhis/client/sdk/core/event/EventControllerImpl.java

@ifoche this PR is not tested. 
I need test it before merge against 2.25_eyeseetea, but it is already merged against the [temporal branch](
https://github.com/EyeSeeTea/dhis2-android-sdk/tree/2.25-EyeSeeTea_temp_changes).
When it is finished i will comment here again

Added push of events returns importSummary

---

core-android/src/main/java/org/hisp/dhis/client/sdk/android/api/persistence/flow/OrganisationUnitToProgramRelationFlow.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/organisationunit/OrganisationUnitStoreImpl.java

Added organisationUnitToProgramRelations

---

core-android/src/main/java/org/hisp/dhis/client/sdk/android/api/D2.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/api/network/NetworkModuleImpl.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/api/persistence/PersistenceModuleImpl.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/api/persistence/flow/OrganisationUnitLevelFlow.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/organisationunit/OrganisationUnitLevelApiClientImpl.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/organisationunit/OrganisationUnitLevelApiClientRetrofit.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/organisationunit/OrganisationUnitLevelInteractor.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/organisationunit/OrganisationUnitLevelInteractorImpl.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/organisationunit/OrganisationUnitLevelStoreImpl.java
core/src/main/java/org/hisp/dhis/client/sdk/core/common/controllers/ControllersModule.java
core/src/main/java/org/hisp/dhis/client/sdk/core/common/controllers/ControllersModuleImpl.java
core/src/main/java/org/hisp/dhis/client/sdk/core/common/network/NetworkModule.java
core/src/main/java/org/hisp/dhis/client/sdk/core/common/persistence/PersistenceModule.java
core/src/main/java/org/hisp/dhis/client/sdk/core/common/preferences/ResourceType.java
core/src/main/java/org/hisp/dhis/client/sdk/core/common/services/ServicesModule.java
core/src/main/java/org/hisp/dhis/client/sdk/core/common/services/ServicesModuleImpl.java
core/src/main/java/org/hisp/dhis/client/sdk/core/organisationunit/OrganisationUnitLevelApiClient.java
core/src/main/java/org/hisp/dhis/client/sdk/core/organisationunit/OrganisationUnitLevelController.java
core/src/main/java/org/hisp/dhis/client/sdk/core/organisationunit/OrganisationUnitLevelControllerImpl.java
core/src/main/java/org/hisp/dhis/client/sdk/core/organisationunit/OrganisationUnitLevelService.java
core/src/main/java/org/hisp/dhis/client/sdk/core/organisationunit/OrganisationUnitLevelServiceImpl.java
core/src/main/java/org/hisp/dhis/client/sdk/core/organisationunit/OrganisationUnitLevelStore.java
models/src/main/java/org/hisp/dhis/client/sdk/models/organisationunit/OrganisationUnitLevel.java

Closes #85
Test it with malariapp feature-new_sdk_organisationUnitLevels

Added OrganisationUnitLevels

---

core/src/main/java/org/hisp/dhis/client/sdk/core/event/EventControllerImpl.java

Added the event in the TrackedEntityDataValue (The TrackedEntityDataValueFlow table was saving null on the event field)

Fix datavalue foreign key

---

core-android/src/main/java/org/hisp/dhis/client/sdk/android/api/persistence/flow/DataElementFlow.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/api/persistence/flow/OrganisationUnitFlow.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/dataelement/DataElementApiClientImpl.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/organisationunit/OrganisationUnitApiClientImpl.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/program/ProgramApiClientImpl.java
models/src/main/java/org/hisp/dhis/client/sdk/models/dataelement/DataElement.java
models/src/main/java/org/hisp/dhis/client/sdk/models/organisationunit/OrganisationUnit.java

Closes #90 
malariappside: feature-new_sdk_polish_2.25
Added the fields Code in dataelements and path in organisationUnits

Added polish changes

---

core-android/src/main/java/org/hisp/dhis/client/sdk/android/api/persistence/PersistenceModuleImpl.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/api/persistence/flow/UserAccountFlow.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/user/UserAccountApiClientImpl.java
core/src/main/java/org/hisp/dhis/client/sdk/core/common/controllers/ControllersModuleImpl.java
core/src/main/java/org/hisp/dhis/client/sdk/core/user/UserAccountControllerImpl.java
models/src/main/java/org/hisp/dhis/client/sdk/models/user/UserAccount.java

Picture branch
https://github.com/EyeSeeTea/pictureapp/tree/feature-new_sdk_download_user_attributes
Picture issue 717

Download user AttributeValue, may be necessary for pull events

---

core-android/src/main/java/org/hisp/dhis/client/sdk/android/api/persistence/flow/EventFlow.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/event/EventInteractor.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/event/EventInteractorImpl.java
core/src/main/java/org/hisp/dhis/client/sdk/core/event/EventControllerImpl.java
models/src/main/java/org/hisp/dhis/client/sdk/models/event/Event.java

Closes #81 and Closes #82 
[malariapp branch](https://github.com/EyeSeeTea/malariapp/tree/feature-new_sdk_fix_push)

2.25 eye see tea fix push

---

core-android/src/main/java/org/hisp/dhis/client/sdk/android/event/EventApiClientImpl.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/event/EventApiClientRetrofit.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/event/EventInteractor.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/event/EventInteractorImpl.java
core/src/main/java/org/hisp/dhis/client/sdk/core/event/EventApiClient.java
core/src/main/java/org/hisp/dhis/client/sdk/core/event/EventController.java
core/src/main/java/org/hisp/dhis/client/sdk/core/event/EventControllerImpl.java
models/src/main/java/org/hisp/dhis/client/sdk/models/event/EventWrapper.java
models/src/main/java/org/hisp/dhis/client/sdk/models/event/Pager.java

Closes #88 
[malariapp branch](https://github.com/EyeSeeTea/malariapp/tree/feature-new_sdk_new_event_variables)

2.25 eye see tea new event variables

---

core-android/src/main/java/org/hisp/dhis/client/sdk/android/api/persistence/flow/OrganisationUnitFlow.java

Recovery the attributeValues from DB if the attributeValues field is null
Closes [malariapp issue](https://github.com/EyeSeeTea/malariapp/issues/1273)

Added query if attributeValues is null on organisationUnitFlow

---

core-android/src/main/java/org/hisp/dhis/client/sdk/android/event/EventApiClientImpl.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/event/EventInteractor.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/event/EventInteractorImpl.java
core/src/main/java/org/hisp/dhis/client/sdk/core/event/EventApiClient.java
core/src/main/java/org/hisp/dhis/client/sdk/core/event/EventController.java
core/src/main/java/org/hisp/dhis/client/sdk/core/event/EventControllerImpl.java
core/src/main/java/org/hisp/dhis/client/sdk/core/event/EventFilters.java

Test this with malaria branch: [feature_new_sdk_refactor_to_event_filters_in_sdk](https://github.com/EyeSeeTea/malariapp/tree/feature_new_sdk_refactor_to_event_filters_in_sdk)
Test this with picture branch: [eature_add_data_pull_of_server_to_the_pull_process](https://github.com/EyeSeeTea/pictureapp/tree/feature_add_data_pull_of_server_to_the_pull_process)

2.25 eye see tea refactor create event filters object

---

core-android/src/main/java/org/hisp/dhis/client/sdk/android/api/persistence/flow/DataElementFlow.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/program/ProgramApiClientImpl.java

Added description field
Related(malariaSide) [this card](https://waffle.io/eyeseetea/malariapp/cards/58a31adc107fcd630135d140)

Pull feedback ("description") field

---

core-android/src/main/java/org/hisp/dhis/client/sdk/android/api/D2.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/api/network/NetworkModuleImpl.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/api/persistence/PersistenceModuleImpl.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/api/persistence/flow/CategoryOptionFlow.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/api/persistence/flow/UserAccountFlow.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/categoryoption/CategoryOptionApiClientImpl.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/categoryoption/CategoryOptionApiClientRetrofit.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/categoryoption/CategoryOptionInteractor.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/categoryoption/CategoryOptionInteractorImp.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/categoryoption/CategoryOptionStoreImpl.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/user/UserAccountApiClientImpl.java
core/src/main/java/org/hisp/dhis/client/sdk/core/categoryoption/CategoryOptionApiClient.java
core/src/main/java/org/hisp/dhis/client/sdk/core/categoryoption/CategoryOptionController.java
core/src/main/java/org/hisp/dhis/client/sdk/core/categoryoption/CategoryOptionControllerImpl.java
core/src/main/java/org/hisp/dhis/client/sdk/core/categoryoption/CategoryOptionService.java
core/src/main/java/org/hisp/dhis/client/sdk/core/categoryoption/CategoryOptionServiceImpl.java
core/src/main/java/org/hisp/dhis/client/sdk/core/categoryoption/CategoryOptionStore.java
core/src/main/java/org/hisp/dhis/client/sdk/core/common/controllers/ControllersModule.java
core/src/main/java/org/hisp/dhis/client/sdk/core/common/controllers/ControllersModuleImpl.java
core/src/main/java/org/hisp/dhis/client/sdk/core/common/network/NetworkModule.java
core/src/main/java/org/hisp/dhis/client/sdk/core/common/persistence/PersistenceModule.java
core/src/main/java/org/hisp/dhis/client/sdk/core/common/preferences/ResourceType.java
core/src/main/java/org/hisp/dhis/client/sdk/core/common/services/ServicesModule.java
core/src/main/java/org/hisp/dhis/client/sdk/core/common/services/ServicesModuleImpl.java
core/src/main/java/org/hisp/dhis/client/sdk/core/user/UserAccountControllerImpl.java
models/src/main/java/org/hisp/dhis/client/sdk/models/category/CategoryOption.java
models/src/main/java/org/hisp/dhis/client/sdk/models/user/UserAccount.java

closes #797 issue from pictureapp

Feature change on volunteer user attribute logic

---

core-android/src/main/java/org/hisp/dhis/client/sdk/android/event/EventInteractorImpl.java
core/src/main/java/org/hisp/dhis/client/sdk/core/event/EventControllerImpl.java

Closes https://github.com/EyeSeeTea/pictureapp/issues/899

Save the import summary errors without events in the reference

---

build.gradle

closes https://github.com/EyeSeeTea/pictureapp/issues/1031

evolve buildToolsVersion

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/settings/SettingsFragment.java
core/src/main/res/layout/fragment_settings.xml
core/src/main/res/values/strings.xml

Closes https://github.com/EyeSeeTea/dhis2-android-eventcapture/issues/2

Added settings export database button and checkbox

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/DataEntryRowTypes.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/EditTextRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/eventdataentry/EventDataEntryFragmentQuery.java
core/src/main/java/org/hisp/dhis/android/sdk/utils/api/ValueType.java
core/src/main/res/values/strings.xml

Closes https://github.com/EyeSeeTea/dhis2-android-eventcapture/issues/11

Added age and percentage types

---

core/src/main/java/org/hisp/dhis/android/sdk/controllers/DhisController.java
core/src/main/java/org/hisp/dhis/android/sdk/controllers/DhisService.java
core/src/main/java/org/hisp/dhis/android/sdk/controllers/LoadingController.java
core/src/main/java/org/hisp/dhis/android/sdk/controllers/ResourceController.java
core/src/main/java/org/hisp/dhis/android/sdk/controllers/metadata/MetaDataController.java
core/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerController.java
core/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerDataLoader.java
core/src/main/java/org/hisp/dhis/android/sdk/network/DhisApi.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/settings/SettingsFragment.java
core/src/main/java/org/hisp/dhis/android/sdk/utils/DbUtils.java
core/src/main/res/layout/fragment_settings.xml
core/src/main/res/values/strings.xml

Closes https://github.com/EyeSeeTea/dhis2-android-eventcapture/issues/3

Added delete remotely deleted events

---

core/src/main/java/org/hisp/dhis/android/sdk/controllers/metadata/MetaDataController.java
core/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerController.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/settings/SettingsFragment.java

Closes https://github.com/EyeSeeTea/dhis2-android-eventcapture/issues/18

On logout wipe all the tables and move to loginactivity

---

ui/build.gradle
ui/src/main/java/org/hisp/dhis/client/sdk/ui/fragments/InformationFragment.java
ui/src/main/res/layout/fragment_information.xml
ui/src/main/res/raw/description.txt
ui/src/main/res/values/strings.xml

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/1

trFeature tracker capture add last commit and about text

---

core/src/main/java/org/hisp/dhis/android/sdk/persistence/models/Event.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/AbsTextWatcher.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/AutoCompleteRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/CheckBoxRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/DatePickerRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/EditTextRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/QuestionCoordinatesRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/Row.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/dialogs/QueryTrackedEntityInstancesResultDialogFragmentQuery.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/eventdataentry/EventDataEntryFragmentQuery.java
core/src/main/res/layout/listview_row_coordinate_picker.xml
core/src/main/res/values/strings.xml

Closes https://github.com/EyeSeeTea/dhis2-android-eventcapture/issues/22

Feature legacy event compulsory complete event control

---

core/src/main/java/org/hisp/dhis/android/sdk/controllers/DhisController.java
core/src/main/java/org/hisp/dhis/android/sdk/controllers/DhisService.java
core/src/main/java/org/hisp/dhis/android/sdk/controllers/LoadingController.java
core/src/main/java/org/hisp/dhis/android/sdk/controllers/SyncStrategy.java
core/src/main/java/org/hisp/dhis/android/sdk/controllers/metadata/MetaDataController.java
core/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerController.java
core/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerDataLoader.java
core/src/main/java/org/hisp/dhis/android/sdk/controllers/wrappers/ProgramWrapper.java
core/src/main/java/org/hisp/dhis/android/sdk/services/PeriodicSynchronizer.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/selectprogram/SelectProgramFragment.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/settings/SettingsFragment.java

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/21

Feature tracker capture make sync work

---

core/src/main/java/org/hisp/dhis/android/sdk/controllers/metadata/MetaDataController.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/settings/SettingsFragment.java

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/22

On logout moves to loginactivity

---

core/src/main/java/org/hisp/dhis/android/sdk/controllers/ResourceController.java
core/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerController.java
core/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerDataLoader.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/dialogs/QueryTrackedEntityInstancesResultDialogFragment.java
core/src/main/res/values/strings.xml

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/28
(2/2)

Added refresh relations and related trackedentintyinstances

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/eventdataentry/EventDataEntryFragmentQuery.java

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/34

Bug tracker capture no event present

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/DataEntryRowFactory.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/DataEntryRowTypes.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/RadioButtonsOptionSetRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/autocompleterow/AutoCompleteOnClearButtonListener.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/autocompleterow/AutoCompleteOnTextChangedListener.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/autocompleterow/AutoCompleteRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/autocompleterow/OnOptionItemSelectedListener.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/dialogs/QueryTrackedEntityInstancesResultDialogFragmentQuery.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/eventdataentry/EventDataEntryFragmentQuery.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/views/FontRadioButton.java
core/src/main/res/layout/listview_row_radio_buttons_option_set.xml

closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/27

create new row and xml for render option set as radio buttons

---

core/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerDataLoader.java

closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/45

Handle exception when an error occurred to sync relationships

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/views/CustomDatePickerDialog.java

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/40

Added custom datepicker

---

core/src/main/java/org/hisp/dhis/android/sdk/controllers/metadata/MetaDataController.java
core/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerController.java
core/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerDataLoader.java
core/src/main/java/org/hisp/dhis/android/sdk/controllers/wrappers/EventsWrapper.java
core/src/main/java/org/hisp/dhis/android/sdk/network/DhisApi.java

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/52

Added update of trackedEntityInstances

---

core/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerController.java
core/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerDataLoader.java

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/53

fix query to check all the events from server and the failed events

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/settings/SettingsFragment.java
core/src/main/res/layout/fragment_settings.xml
core/src/main/res/values/strings.xml

closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/68

reduce settings buttons size and unify term that was repeated

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/settings/SettingsFragment.java
core/src/main/res/values-es/strings.xml
core/src/main/res/values-fr/strings.xml
core/src/main/res/values/donottranslate.xml
core/src/main/res/values/strings.xml
ui/src/main/res/values-es/strings.xml
ui/src/main/res/values-fr/strings.xml
ui/src/main/res/values/donottranslate.xml

closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/69

Add Spanish and French translations

---

core/build.gradle
core/src/main/java/org/hisp/dhis/android/sdk/services/PeriodicSynchronizerAutoStarter.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/dialogs/QueryTrackedEntityInstancesResultDialogFragment.java
core/src/main/java/org/hisp/dhis/android/sdk/utils/api/CodeGenerator.java
core/src/main/res/layout/activity_login.xml
core/src/main/res/layout/activity_splash.xml
core/src/main/res/menu/menu_data_entry.xml

closes https://github.com/EyeSeeTea/dhis2-android-eventcapture/issues/28

fix lint errors

---

core/src/main/java/org/hisp/dhis/android/sdk/persistence/models/BaseIdentifiableObject.java

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/73

Added createdAtClient and lastUpdatedAtClient setters

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/eventdataentry/EventDataEntryFragment.java
core/src/main/res/values-es/strings.xml
core/src/main/res/values-fr/strings.xml
core/src/main/res/values/strings.xml

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/78

Change text value complete by en-roll

---

core/src/main/res/layout/listview_row_relationship.xml
core/src/main/res/values/colors.xml

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/76

Added blue color for the TEI linkable text

---

core/src/main/java/org/hisp/dhis/android/sdk/controllers/metadata/MetaDataController.java

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/86 and closes 
EyeSeeTea/dhis2-android-trackercapture#102

Bug fix optionset sync

---

ui/src/main/res/raw/description.txt

closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/101

Remove EyeSeeTea Ltd from About Us

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/StatusRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/eventdataentry/EventDataEntryFragment.java

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/100

fixed complete string on event complete button

---

core/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerController.java
core/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerDataSender.java

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/92

Bug tracker capture cancel enrollment sync problems

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/EmailAddressEditTextRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/EventCoordinatesRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/QuestionCoordinatesRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/dataentry/DataEntryFragment.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/eventdataentry/EventDataEntryFragment.java
core/src/main/res/layout/dialog_fragment_validation_errors.xml
core/src/main/res/values-es/strings.xml
core/src/main/res/values-fr/strings.xml
core/src/main/res/values/strings.xml

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/97
(2/2)

Feature tracker capture invalid coordinates treatment

---

core/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerDataLoader.java

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/96

Bug tracker capture events appear without ou

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/dialogs/QueryTrackedEntityInstancesResultDialogAdapter.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/dialogs/QueryTrackedEntityInstancesResultDialogFragment.java
core/src/main/res/layout/two_horizontal_textviews.xml
core/src/main/res/values/donottranslate.xml

Close https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/112

Showing in the same textView the entities attributes in online search.

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/EnrollmentDatePickerRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/EventDatePickerRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/EventDueDatePickerRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/IncidentDatePickerRow.java

Close https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/107

Set the date shown in the text field whe open the date picker.

---

core/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerController.java

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/115
(1/2)

Added last Enrollment query

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/EmailAddressEditTextRow.java

Close https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/122

Solving bug with email pattern to check if  it is a valid email.

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/AutoCompleteRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/CheckBoxRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/DatePickerRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/EditTextRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/RadioButtonsRow.java

Closes https://github.com/EyeSeeTea/dhis2-android-eventcapture/issues/32

Fixed: program rule error text

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/DataEntryRowTypes.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/EditTextRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/eventdataentry/EventDataEntryFragmentQuery.java
core/src/main/java/org/hisp/dhis/android/sdk/utils/api/ValueType.java
core/src/main/res/values/strings.xml

Closes https://github.com/EyeSeeTea/dhis2-android-eventcapture/issues/34

Bug time type not suppported

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/eventdataentry/EventDataEntryFragmentQuery.java

Close https://github.com/EyeSeeTea/dhis2-android-eventcapture/issues/44

Not allowing to edit the not supported value types.

---

core/src/main/java/org/hisp/dhis/android/sdk/controllers/wrappers/ProgramWrapper.java
core/src/main/java/org/hisp/dhis/android/sdk/persistence/models/ProgramStageSection.java

Closes https://github.com/EyeSeeTea/dhis2-android-eventcapture/issues/47

support 2.27 programStageDataElements grouped as dataElements by sections

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/DataValueAdapter.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/EditTextRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/dataentry/DataEntryFragment.java

Close https://github.com/EyeSeeTea/dhis2-android-eventcapture/issues/49

Bug next focus down edittext

---

core/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerController.java
core/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerDataLoader.java
core/src/main/java/org/hisp/dhis/android/sdk/persistence/models/BaseIdentifiableObject.java

Closes https://github.com/EyeSeeTea/dhis2-android-eventcapture/issues/43

Add the edited events to the server remote remove sync

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/AutoCompleteRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/EditTextRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/dataentry/RowValueChangedEvent.java

closes https://github.com/EyeSeeTea/dhis2-android-eventcapture/issues/40

Bug viewholder pattern failure

---

core/src/main/java/org/hisp/dhis/android/sdk/persistence/models/Event.java

Closes https://github.com/EyeSeeTea/dhis2-android-eventcapture/issues/55

add simple date format

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/eventdataentry/EventDataEntryFragment.java

Closes https://github.com/EyeSeeTea/dhis2-android-eventcapture/issues/57

Init gps if some dataelement is a coordinate question

---

core/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerController.java
core/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerDataSender.java
core/src/main/java/org/hisp/dhis/android/sdk/network/DhisApi.java
core/src/main/java/org/hisp/dhis/android/sdk/persistence/models/Event.java
core/src/main/res/values/strings.xml

Closes https://github.com/EyeSeeTea/dhis2-android-eventcapture/issues/60

Feature legacy event delete locally deleted events

---

core/src/main/java/org/hisp/dhis/android/sdk/controllers/wrappers/ProgramWrapper.java

Closes https://github.com/EyeSeeTea/dhis2-android-eventcapture/issues/63

Feature legacy event order sectiondataelement

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/DataValueAdapter.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/events/EventItemRow.java
core/src/main/java/org/hisp/dhis/android/sdk/utils/api/ProgramRuleActionType.java

Close https://github.com/EyeSeeTea/dhis2-android-eventcapture/issues/64

Bug hidden fields not reset

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/common/AbsProgramRuleFragment.java
core/src/main/java/org/hisp/dhis/android/sdk/utils/services/ProgramRuleService.java

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/141

fixed null programrules content crash

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/QuestionCoordinatesRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/eventdataentry/EventDataEntryFragment.java

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/127

Bug gps problems

---

core/src/main/java/org/hisp/dhis/android/sdk/controllers/ErrorType.java
core/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerController.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/dataentry/DataEntryFragment.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/eventdataentry/EventDataEntryFragment.java
core/src/main/res/values-es/strings.xml
core/src/main/res/values-fr/strings.xml
core/src/main/res/values/strings.xml

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/137
(2/2)

Add unique validation error and refactor validation errors

---

core/src/main/res/layout/listview_trackedentityinstance_item.xml

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/166
(2/2)

fix new tei layout

---

core/src/main/java/org/hisp/dhis/android/sdk/controllers/DhisController.java
core/src/main/java/org/hisp/dhis/android/sdk/synchronization/domain/app/SyncAppUseCase.java
core/src/main/java/org/hisp/dhis/android/sdk/synchronization/domain/trackedentityinstance/TrackedEntityInstanceSynchronizer.java

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/160

Feature tracker capture refactor sync app

---

models/src/main/java/org/hisp/dhis/client/sdk/models/event/Event.java

Closes https://github.com/EyeSeeTea/malariapp/issues/1541

Added Visited status

---

core/src/main/java/org/hisp/dhis/android/sdk/persistence/models/Event.java
core/src/main/java/org/hisp/dhis/android/sdk/synchronization/data/event/EventRemoteDataSource.java
core/src/main/java/org/hisp/dhis/android/sdk/synchronization/domain/event/EventSynchronizer.java

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/163

Refactor null events

---

core/src/main/java/org/hisp/dhis/android/sdk/controllers/tracker/TrackerController.java

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/154

Fix query to count the number of repeated values

---

core/src/main/java/org/hisp/dhis/android/sdk/persistence/models/ImportSummary.java
core/src/main/java/org/hisp/dhis/android/sdk/synchronization/data/event/EventRemoteDataSource.java
core/src/main/java/org/hisp/dhis/android/sdk/synchronization/data/event/EventRepository.java
core/src/main/java/org/hisp/dhis/android/sdk/synchronization/domain/common/Synchronizer.java
core/src/main/java/org/hisp/dhis/android/sdk/synchronization/domain/event/EventSynchronizer.java
core/src/main/java/org/hisp/dhis/android/sdk/synchronization/domain/event/IEventRepository.java

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/173

Feature event batch result treatment

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/dataentry/DataEntryFragment.java

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/181

on scroll clear focus and hide keyboard

---

core/src/main/java/org/hisp/dhis/android/sdk/controllers/metadata/MetaDataController.java
core/src/main/java/org/hisp/dhis/android/sdk/persistence/models/SystemInfo.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/QuestionCoordinatesRow.java
ui/src/main/java/org/hisp/dhis/client/sdk/ui/AppPreferences.java
ui/src/main/java/org/hisp/dhis/client/sdk/ui/AppPreferencesImpl.java

Close https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/182

Change coordinates saved format if server version is 2.25

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/AboutUsFragment.java
core/src/main/res/layout/fragment_about_us.xml
core/src/main/res/values/strings.xml

Closes https://github.com/EyeSeeTea/dhis2-android-eventcapture/issues/73

Added server info into about us fragment

---

core/src/main/java/org/hisp/dhis/android/sdk/controllers/LoadingController.java
core/src/main/java/org/hisp/dhis/android/sdk/events/UiEvent.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/activities/LoginActivity.java

Closes https://github.com/EyeSeeTea/dhis2-android-eventcapture/issues/74

Move initial pull after login before move to mainactivity

---

core-android/src/main/java/org/hisp/dhis/client/sdk/android/api/persistence/DbDhis.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/api/persistence/flow/AttributeFlow.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/api/persistence/flow/AttributeValueFlow.java

Closes https://github.com/EyeSeeTea/malariapp/issues/1620
(1/2)

Feature bugfixing override uid

---

core-android/src/main/java/org/hisp/dhis/client/sdk/android/api/persistence/DbDhis.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/api/persistence/flow/OrganisationUnitFlow.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/api/persistence/migrations/Migration4AddCoordinatesOrganisationUnitFlow.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/organisationunit/OrganisationUnitApiClientImpl.java
models/src/main/java/org/hisp/dhis/client/sdk/models/organisationunit/OrganisationUnit.java

Close https://github.com/EyeSeeTea/pictureapp/issues/1538

Feature ou tree question

---

models/src/main/java/org/hisp/dhis/client/sdk/models/common/importsummary/ImportSummary.java

closes https://github.com/EyeSeeTea/pictureapp/issues/1556

add warning state to avoid crash on 2.27 servers

---

core-android/src/main/java/org/hisp/dhis/client/sdk/android/organisationunit/OrganisationUnitApiClientImpl.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/organisationunit/OrganisationUnitApiClientRetrofit.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/organisationunit/OrganisationUnitInteractor.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/organisationunit/OrganisationUnitInteractorImpl.java
core-android/src/main/java/org/hisp/dhis/client/sdk/android/organisationunit/OrganisationUnitStoreImpl.java
core/src/main/java/org/hisp/dhis/client/sdk/core/common/controllers/SyncStrategy.java
core/src/main/java/org/hisp/dhis/client/sdk/core/organisationunit/OrganisationUnitApiClient.java
core/src/main/java/org/hisp/dhis/client/sdk/core/organisationunit/OrganisationUnitController.java
core/src/main/java/org/hisp/dhis/client/sdk/core/organisationunit/OrganisationUnitControllerImpl.java
core/src/main/java/org/hisp/dhis/client/sdk/core/organisationunit/OrganisationUnitService.java
core/src/main/java/org/hisp/dhis/client/sdk/core/organisationunit/OrganisationUnitServiceImpl.java
core/src/main/java/org/hisp/dhis/client/sdk/core/organisationunit/OrganisationUnitStore.java

Closes https://github.com/EyeSeeTea/pictureapp/issues/1551
(1/2)

Feature add organisation unit with descendants call

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/activities/LoginActivity.java

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/202

move pull from mainactivity to login

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/EventDatePickerRow.java

Close https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/209

Showing values if deleting the event date an them putting the same date.

---

core/src/main/java/org/hisp/dhis/android/sdk/persistence/models/Enrollment.java

Close https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/203

Putting default date format when auto-generating events

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/eventdataentry/EventDataEntryFragment.java

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/205

Tracker capture feature open next valid event

---

core/src/main/java/org/hisp/dhis/android/sdk/events/OnTeiDownloadedEvent.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/eventdataentry/EventDataEntryFragment.java
core/src/main/java/org/hisp/dhis/android/sdk/utils/UiUtils.java
core/src/main/res/values-es/strings.xml
core/src/main/res/values-fr/strings.xml
core/src/main/res/values/strings.xml
ui/src/main/res/values-es/strings.xml
ui/src/main/res/values-fr/strings.xml
ui/src/main/res/values/strings.xml

Close https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/201

Check strings translations.

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/views/CustomDatePickerDialog.java
core/src/main/java/org/hisp/dhis/android/sdk/utils/services/ProgramIndicatorService.java
core/src/main/java/org/hisp/dhis/android/sdk/utils/support/ExpressionUtils.java

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/204

Tracker capture custom date picker title

---

core/src/main/java/org/hisp/dhis/android/sdk/persistence/Dhis2Database.java
core/src/main/java/org/hisp/dhis/android/sdk/persistence/migrations/version7/Version7MigrationEventColumn.java
core/src/main/java/org/hisp/dhis/android/sdk/persistence/migrations/version7/Version7MigrationProgramColumns.java
core/src/main/java/org/hisp/dhis/android/sdk/persistence/models/Event.java
core/src/main/java/org/hisp/dhis/android/sdk/persistence/models/Program.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/DataEntryRowTypes.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/EditTextRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/EventCoordinatesRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/QuestionCoordinatesRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/StatusRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/eventdataentry/EventDataEntryFragment.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/eventdataentry/EventDataEntryFragmentForm.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/eventdataentry/EventSaveThread.java
core/src/main/res/values/strings.xml

Closes https://github.com/EyeSeeTea/dhis2-android-eventcapture/issues/75

Legacy event add completion expiry date

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/DataValueAdapter.java

Closes https://github.com/EyeSeeTea/dhis2-android-eventcapture/issues/69

Feature legacy event delete optionset when on triggered hide program rule

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/EditTextRow.java

Closes https://github.com/EyeSeeTea/dhis2-android-eventcapture/issues/87

Fix not supported row setted as editable

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/DataValueAdapter.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/RadioButtonsRow.java

Closes https://github.com/EyeSeeTea/dhis2-android-eventcapture/issues/86

fix hide radiobutton by program rule

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/activities/LoginActivity.java
core/src/main/res/layout/activity_login.xml
core/src/main/res/layout/fragment_data_entry.xml
core/src/main/res/values/strings.xml

Closes https://github.com/EyeSeeTea/dhis2-android-eventcapture/issues/83

Added pull message after login

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/activities/LoginActivity.java

closes EyeSeeTea/dhis2-android-eventcapture#84

Feature event capture hide keyboard after login

---

core/src/main/java/org/hisp/dhis/android/sdk/controllers/DhisController.java
core/src/main/java/org/hisp/dhis/android/sdk/controllers/LoadingController.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/activities/LoginActivity.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/selectprogram/SelectProgramFragmentPreferences.java

Closes https://github.com/EyeSeeTea/dhis2-android-eventcapture/issues/85

Clean preferences and pull events after metadata

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/DataValueAdapter.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/EditTextRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/dataentry/DataEntryFragment.java
core/src/main/res/layout/listview_row_edit_text.xml

Closes https://github.com/EyeSeeTea/dhis2-android-eventcapture/issues/88

Fix next keyboard action for edittext

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/DataValueAdapter.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/common/AbsProgramRuleFragment.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/common/IProgramRuleFragmentHelper.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/dataentry/DataEntryFragment.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/eventdataentry/EventDataEntryRuleHelper.java

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/207
(sorry, I used inadvertently hyphens instead of underscores for the branch name)

Disable form rows of calculated fields

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/eventdataentry/EventDataEntryFragment.java

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/223

remove event without due date or report date when the user do back

---

core/src/main/java/org/hisp/dhis/android/sdk/persistence/Dhis2Database.java
core/src/main/java/org/hisp/dhis/android/sdk/persistence/migrations/version14/Version17MigrationCreatePteaRenderOptionsAsRadioField.java
core/src/main/java/org/hisp/dhis/android/sdk/persistence/migrations/version17/Version17MigrationCreateRenderOptionsAsRadioField.java
core/src/main/java/org/hisp/dhis/android/sdk/persistence/models/ProgramStageDataElement.java
core/src/main/java/org/hisp/dhis/android/sdk/persistence/models/ProgramTrackedEntityAttribute.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/dialogs/QueryTrackedEntityInstancesResultDialogFragmentQuery.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/eventdataentry/EventDataEntryFragmentQuery.java

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/222

Feature tracker capture add new render as radiobutton

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/DataEntryRowFactory.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/DataEntryRowTypes.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/DatePickerRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/DateTimePickerRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/TimePickerRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/URLEditTextRow.java
core/src/main/java/org/hisp/dhis/android/sdk/utils/api/ValueType.java
core/src/main/res/layout/time_date_picker.xml
core/src/main/res/values-es/strings.xml
core/src/main/res/values-fr/strings.xml
core/src/main/res/values/strings.xml
ui/src/main/java/org/hisp/dhis/client/sdk/ui/models/FormEntityEditText.java
ui/src/main/java/org/hisp/dhis/client/sdk/ui/rows/EditTextRowView.java

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/224

Feature add new types

---

core/build.gradle
core/src/main/java/org/hisp/dhis/android/sdk/utils/support/ExpressionUtils.java
core/src/main/java/org/hisp/dhis/android/sdk/utils/support/math/ExpressionFunctions.java
core/src/test/java/org/hisp/dhis/android/sdk/utils/support/math/ExpressionFunctionsTest.java

Fixes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/219
- Fixes & tests for existing functions: zing, oizp, zpvc, condition, daysBetween, weeksBetween, monthsBetween, yearsBetween, floor, modulus, concatenate, addDays, count, countIfZeroPos, countIfValue, ceil, round, hasValue, lastEventDate, validatePattern, validatePattern.
- Implementation & tests of existing functions: left, right, length, split, substring
Functions tested in dhis-web-tracker-capture and dhis2-android-trackercapture to check similar behaviour.
To run all the tests (CLI): `$ ./gradlew test --info"
To run all only tests of a specific project: `$ ./gradlew core:test --info"

Feature tracker capture improve program rules

---

core/src/main/java/org/hisp/dhis/android/sdk/persistence/migrations/version17/Version17MigrationCreateProgramStageField.java
core/src/main/java/org/hisp/dhis/android/sdk/persistence/models/ProgramRuleAction.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/DataValueAdapter.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/DateTimePickerRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/Row.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/dataentry/TimePickerRow.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/common/AbsProgramRuleFragment.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/common/IProgramRuleFragmentHelper.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/dataentry/DataEntryFragment.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/eventdataentry/EventDataEntryFragment.java
core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/eventdataentry/EventDataEntryRuleHelper.java
core/src/main/res/values-es/strings.xml
core/src/main/res/values-fr/strings.xml
core/src/main/res/values/strings.xml

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/220
Added: 
Warning on complete
Hide program stage
error on complete
make field mandatory
(2/2)

Feature tracker capture add program rules

---

core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/eventdataentry/EventDataEntryFragment.java

Closes https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/233

Feature fix warning on complete action executed when set as editable a event
